/*
 * Natural-Language File Comment:
 * File Role: Prisma tooling config (migration/generate runtime settings).
 * Project Flow Link: 'prisma.config.ts' app ke end-to-end workflow ka specific block handle karta hai.
 * Read Order: imports -> main function/component -> data flow/return -> side effects (if any).
 */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
